name: Build and Release - Rocom

on:
  push:
    tags:
      - "v*" # 当推送以 v 开头的标签时触发，如 v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须赋予写入权限以创建 Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run set_rocom
          npm run build

      # 将打包后的 dist 目录压缩为 zip，方便用户下载
      - name: Archive dist
        run: zip -r release-build.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-build.zip
          name: ${{ github.ref_name }}+rocom
          tag_name: ${{ github.ref_name }}+rocom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
